repos:
- hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: pretty-format-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-vcs-permalinks
  - files: .*\.(yaml|eyaml|yml)$
    id: check-yaml
  - id: check-toml
  - id: check-xml
  - args:
    - --allow-missing-credentials
    id: detect-aws-credentials
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - files: ^[requirements]\.txt$
    id: file-contents-sorter
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - files: \.(py|sh|md|yaml)$
    id: forbid-tabs
  - args:
    - --whitespaces-count
    - '2'
    files: \.(py|sh|md|yaml)$
    id: remove-tabs
  repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
- hooks:
  - args:
    - --indent
    - '    '
    - --bullets "-"
    - -i
    id: markdown-toc
  repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.2
- hooks:
  - id: bundler-audit
  - id: fasterer
  - id: forbid-binary
  - exclude: ^.*(?<!\.go)$
    id: forbid-space-in-indent
  - id: git-dirty
  - id: markdownlint
  - id: reek
  - id: require-ascii
    exclude: (.*\.md|motd)$
  - id: rubocop
  - id: script-must-have-extension
  - id: script-must-not-have-extension
  - args:
    - -e
    - SC2086
    id: shellcheck
  - id: shfmt
  repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
- hooks:
  - description: Runs hadolint to lint Dockerfiles
    entry: hadolint
    id: hadolint
    language: system
    name: Lint Dockerfiles
    types:
    - dockerfile
  repo: https://github.com/hadolint/hadolint
  rev: v2.14.0
- hooks:
  - id: check-useless-excludes
  repo: meta
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.9.1
- hooks:
  - id: fmt
  - id: clippy
  - id: cargo-check
  repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
- hooks:
  - id: cargo-test
    name: Cargo Test
    entry: cargo test
    language: system
    files: \.rs$
    pass_filenames: false
  repo: local
